name: Hugo
description: Build your Hugo application for deployment
author: utahcon
branding:
  icon: package
  color: orange
inputs:
  baseURL:
    description: hostname (and path) to the root, e.g. http://spf13.com/
    required: false
  buildDrafts:
    description: include content marked as draft
    required: false
  buildExpired:
    description: include expired content
    required: false
  buildFuture:
    description: include content with publishdate in the future
    required: false
  config:
    description: config file (default is path/config.yaml|json|toml)
    required: false
  configDir:
    description: config dir (default "config")
    required: false
  contentDir:
    description: filesystem path to content directory
    required: false
  debug:
    description: debug output
    required: false
  enableGitInfo:
    description: add Git revision, date and author info to the pages
    required: false
  environment:
    description: build environment
    required: false
  i18n-warnings:
    description: print missing translations
    required: false
  ignoreVendor:
    description: ignores any _vendor directory
    required: false
  layoutDir:
    description: filesystem path to layout directory
    required: false
  minify:
    description: (ignored) minify any supported output format (HTML, XML etc.)
    required: false
    default: false
  noChmod:
    description: don't sync permission mode of files
    required: false
  noTimes:
    description: don't sync modification time of files
    required: false
  path-warnings:
    description: print warnings on duplicate target paths etc.
    required: false
  source:
    description: filesystem path to read files relative from
    required: false
  templateMetrics:
    description: display metrics about template executions
    required: false
  templateMetricsHints:
    description: calculate some improvement hints when combined with --templateMetrics
    required: false
  theme:
    description: themes to use (located in /themes/THEMENAME/)
    required: false
  themesDir:
    description: filesystem path to themes directory
    required: false
  verbose:
    description: verbose output
    required: false
    default: true

runs:
  using: docker
  image: docker://utahcon/hugo
  args:
    - ${{ inputs.baseURL }}
    - ${{ inputs.buildDrafts }}
    - ${{ inputs.buildExpired }}
    - ${{ inputs.buildFuture }}
    - ${{ inputs.config }}
    - ${{ inputs.configDir }}
    - ${{ inputs.contentDir }}
    - ${{ inputs.debug }}
    - ${{ inputs.enableGitInfo }}
    - ${{ inputs.environment }}
    - ${{ inputs.i18n-warnings }}
    - ${{ inputs.ignoreVendor }}
    - ${{ inputs.layoutDir }}
    - ${{ inputs.minify }}
    - ${{ inputs.noChmod }}
    - ${{ inputs.noTimes }}
    - ${{ inputs.path-warnings }}
    - ${{ inputs.source }}
    - ${{ inputs.templateMetrics }}
    - ${{ inputs.templateMetricsHints }}
    - ${{ inputs.theme }}
    - ${{ inputs.themesDir }}
    - ${{ inputs.verbose }}
