name: Hugo
description: Build your Hugo application for deployment
author: utahcon

branding:
  icon: package
  color: orange

inputs: %%INPUTS%%

runs:
  using: docker
  image: docker://utahcon/hugo:%%VERSION%%
  args: %%ARGS%%
