%% workflow
graph LR
    %% triggers
    subgraph triggers
        watch --> owner{owner}
        owner --> action
        cron[cron<br>0 0 * * *] --> action
    end

    %% Jobs
    subgraph TD jobs
        action --> a
        action --> b
        subgraph steps
            a[checkout action-hugo]
            b[checkout hugo]
            c[hugo version]
            d[action version]
            version_match{version<br>match}
            build_version[BUILD_VERSION]
            tag[tag]
            checkout[checkout]
            commit[commit]
            push[push]

            a --> c
            b --> d
            c --> version_match
            d --> version_match
            version_match --no--> End
            version_match --yes--> build_version
            build_version --> tag
            tag --> checkout
            checkout --> commit
            commit --> push
        end
    end
