name: Hugo Builder

on:
  push:
    branches:
      - build

jobs:
  checkout_action_hugo:
    name: Checkout action-hugo
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Action
        uses: actions/checkout@v2.3.1

      - name: Checkout Hugo
        uses: actions/checkout@v2.3.1
        with:
          repository: gohugoio/hugo
          submodules: true
          fetch-depth: 0
          path: hugo

      - id: get_version
        name: Get Version
        run: |
          BUILD_VERSION=$(cat BUILD_VERSION)

          (
            cd hugo || exit
            git checkout ${BUILD_VERSION}
            go install --tags extended
            mv $HOME/go/bin/hugo .
            chmod +x hugo
          )

          git push origin :refs/tags/release-${BUILD_VERSION}
          git push origin :release-${BUILD_VERSION}
          git checkout -b release-${BUILD_VERSION}

          git push origin :refs/tags/${BUILD_VERSION}

          sed "s/%%version%%/${BUILD_VERSION}/" action.yml.tmp > action.yml
          git add action.yml
          git commit -m "Updating action.yml with version ${BUILD_VERSION}"

      - name: Build and Push to Docker Hub
        uses: docker/build-push-action@v1.1.0
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
          repository: utahcon/hugo
          dockerfile: Containerfile
          tags: ${BUILD_VERSION}
