name: Hugo Builder

on:
  push:
    branch:
      - build

jobs:
  checkout_action_hugo:
    name: Checkout action-hugo
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2.3.1

      - id: get_version
        name: Get Version
        run: |
          echo "::set-output name=hugo_version::$(cat BUILD_VERSION)"

      - name: Check out the repo
        uses: actions/checkout@v2.3.1
        with:
          ref: ${{ steps.get_version.outputs.version }}
          repository: gohugoio/hugo
          submodules: true
          fetch-depth: 0

      - name: Build Hugo
        run: |
          cd hugo || exit
          go install --tags extended
          mv $HOME/go/bin/hugo .
          chmod +x hugo

      - name: Checkout Build Branch
        run: |
          git push origin :refs/tags/release-${{ steps.get_version.outputs.version }}
          git push origin :release-${{ steps.get_version.outputs.version }}
          git checkout -b release-${{ steps.get_version.outputs.version }}

      - name: Clean version tag
        run: |
            git push origin :refs/tags/${{ steps.get_version.outputs.version }}

      - name: Create action.yml
        run: |
          sed "s/%%version%%/${{ steps.get_version.outputs.version }}/" action.yml.tmp > action.yml
          git add action.yml
          git commit -m "Updating action.yml with version ${{ steps.get_version.outputs.version }}"

      - name: Build and Push to Docker Hub
        uses: docker/build-push-action@v1.1.0
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
          repository: utahcon/hugo
          dockerfile: Containerfile
          tags: ${{ steps.get_version.outputs.version }}
