name: Hugo Builder

on:
  push:
    branches:
      - build

jobs:
  checkout_action:
    name: Checkout action-hugo
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.version.outputs.version }}
    steps:
      - uses: actions/checkout@v2.3.1

      - name: Tag and Branch
        run: |
          VERSION=$(cat BUILD_VERSION)
          echo "::set-output name=version::${VERSION}"

          git fetch --all

          git tag
          for T in $(git tag); do
            if [ "${T}" == "${VERSION}" ]; then
              git push origin :refs/tags/${VERSION}
            fi
          done

          git branch -r
          for B in $(git branch -r); do
            if [ "${B}" == "origin/release-${VERSION}" ]; then
              git push origin :release-${VERSION}
            fi
          done

          git checkout -b release-${VERSION}
          git config --global user.email "github@utahcon.com"
          git config --global user.name "Adam Barrett"

          sed "s/%%version%%/${VERSION}/" action.yml.tmp > action.yml
          git add action.yml
          git commit -m "Updating action.yml with version ${VERSION}"
          git tag -af ${VERSION} -m "Version ${VERSION}"
          git push origin release-${VERSION} --tags --force

      - uses: actions/upload-artifact@v2
        with:
          name: action-hugo
          path: .

  checkout_action_hugo:
    name: Checkout and build Hugo
    runs-on: ubuntu-latest
    needs: checkout_action
    steps:
      - name: Checkout Hugo
        uses: actions/checkout@v2.3.1
        with:
          repository: gohugoio/hugo
          submodules: true
          fetch-depth: 0

      - name: Build Hugo
        run: |
          git checkout ${{ needs.checkout_action.outputs.version }}
          go install --tags extended
          mv $HOME/go/bin/hugo .
          chmod +x hugo

      - uses: actions/upload-artifact@v2
        with:
          name: hugo
          path: $HOME/go/bin/hugo

  build_and_push_container:
    name: Build and push container
    runs-on: ubuntu-latest
    needs:
      - checkout_action
      - checkout_action_hugo
    steps:
      - uses: actions/download-artifact@v2
        with:
          name: action-hugo
          path: .

      - uses: actions/download-artifact@v2
        with:
          name: hugo
          path: .

      - uses: docker/build-push-action@v1.1.0
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
          repository: utahcon/hugo
          dockerfile: Containerfile
          tags: ${{ needs.checkout_action.outputs.version }}
