name: Hugo Version Checker

on:
  watch:
    types: [started] # combined with if: github.actor line allows me to kick of builds with stars
  schedule:
    - cron: "0 * * * *"

jobs:
  action:
    if: github.actor == github.event.repository.owner.login
    name: Checkout Action
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Action
        uses: actions/checkout@v2.3.1
        with:
          path: action
          token: ${{ secrets.PERSONAL_GITHUB_TOKEN }}

      - name: Checkout Hugo Repo
        uses: actions/checkout@v2.3.1
        with:
          path: hugo
          repository: gohugoio/hugo
          submodules: true
          fetch-depth: 0

      - name: Check Version and Kick Build
        run: |
          H_VERSION=$(
            cd hugo
            git fetch --all 1>&2
            git tag | sort -rV | head -n 1
          )

          (
            cd action
            git fetch --all 1>&2

            for AV in $(git tag); do
              echo "'${AV}' == '${H_VERSION}'"
              if [ "${AV}" == "${H_VERSION}" ]; then
                exit
              fi
            done

            echo "${H_VERSION}" > BUILD_VERSION

            git config --global user.email "github@utahcon.com"
            git config --global user.name "Adam Barrett"

            git push origin :refs/tags/build || true
            git push origin :build || true

            git checkout -b build
            git add BUILD_VERSION
            git commit -m "Kicking off build for ${H_VERSION}"
            git push origin build --force
          )
