name: Hugo Version Checker

on:
  watch:
    types: [started]
  schedule:
    - cron: "0 0 * * *"

jobs:
  hugo:
    if: github.actor == github.event.repository.owner.login
    name: Checkout Hugo
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.get_hugo_version.outputs.version }}
    steps:
      - name: Checkout Hugo Repo
        uses: actions/checkout@v2.3.1
        with:
          path: hugo
          repository: gohugoio/hugo
          submodules: true
          fetch-depth: 0

      - id: get_hugo_version
        name: Check Hugo Version
        run: |
          cd hugo
          echo "::set-output name=version::$(git tag | sort -rV | head -n 1)"

  builder:
    name: Checkout Builder
    runs-on: ubuntu-latest
    outputs:
      versions: ${{ steps.get_builder_version.outputs.versions }}
    steps:
      - name: Checkout Builder
        uses: actions/checkout@v2.3.1
        with:
          path: builder

      - id: get_builder_version
        name: Get Builder Version
        run: |
          cd builder
          echo "::set-output name=versions::$(git tag | sort -rV)"

  check_versions:
    name: Check Versions
    runs-on: ubuntu-latest
    needs:
      - hugo
      - builder
    steps:
      - name: Check Hugo against Builder
        run: |
          for BV in "${{ needs.builder.outputs.versions }}"; do
            if [ "${BV}" == "${{ needs.hugo.outputs.version }}" ]; then
              exit
            fi
          done

          echo "Create Builder Version: ${{ needs.hugo.outputs.version }}"
          echo "${{ needs.hugo.outputs.version}}" > BUILD_VERSION
          git checkout -b build
          git add BUILD_VERSION
          git commit -m "Kicking off build for ${{ needs.hugo.outputs.version }}"
          git push origin ${{ needs.hugo.outputs.version }}
