name: Hugo Version Checker

on:
  watch:
    types: [started]
  schedule:
    - cron: "0 0 * * *"

jobs:
  action:
    if: github.actor == github.event.repository.owner.login
    name: Checkout Action
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Action
        uses: actions/checkout@v2.3.1
        with:
          path: action

      - name: Checkout Hugo Repo
        uses: actions/checkout@v2.3.1
        with:
          path: hugo
          repository: gohugoio/hugo
          submodules: true
          fetch-depth: 0

      - name: Check Version and Kick Build
        run: |
          A_VERSIONS=(
            cd action
            git fetch --all 2>&1
            git tag | sort -rV
          )

          H_VERSION=(
            cd hugo
            git fetch --all 2>&1
            git tag | sort -rV | head -n 1
          )

          for AV in "${A_VERSIONS}"; do
            if [ "${AV}" == "${H_VERSION}" ]; then
              exit
            fi
          done

          (
            cd action
            echo "${H_VERSION}" > BUILD_VERSION
            git checkout -b build
            git add BUILD_VERSION
            git commit -m "Kicking off build for ${H_VERSION}"
            git push origin ${H_VERSION}
          )
