name: Hugo Version Checker

on:
  watch:
    types: [started]
  schedule:
    - cron: "0 * * * *"

jobs:
  action:
    if: github.actor == github.event.repository.owner.login
    name: Checkout Action
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Action
        uses: actions/checkout@v2.3.1
        with:
          path: action
          token: ${{ secrets.PERSONAL_GITHUB_TOKEN }}

      - name: Checkout Hugo Repo
        uses: actions/checkout@v2.3.1
        with:
          path: hugo
          repository: gohugoio/hugo
          submodules: true
          fetch-depth: 0

      - name: Check Version and Kick Build
        run: |
          (
            cd action
            git fetch --all
            git push origin :refs/tags/build || true
            git push origin :build || true
          )

          A_VERSIONS=$(
            cd action
            git tag | sort -rV
          )
          echo "Action: ${A_VERSIONS}"

          (
            cd hugo
            git fetch --all
          )

          H_VERSION=$(
            cd hugo
            git tag | sort -rV | head -n 1
          )
          echo "Hugo: ${H_VERSION}"

          for AV in "${A_VERSIONS}"; do
            if [ "${AV}" == "${H_VERSION}" ]; then
              exit
            fi
          done

          (
            cd action
            echo "${H_VERSION}" > BUILD_VERSION
            git config --global user.email "github@utahcon.com"
            git config --global user.name "Adam Barrett"
            git checkout -b build
            git add BUILD_VERSION
            git commit -m "Kicking off build for ${H_VERSION}"
            git push origin build --force
          )
