name: Hugo Builder

on:
  push:
    branch:
      - master

jobs:
  checkout_and_build:
    name: Pull and Build Repo
    runs-on: ubuntu-latest
    steps:
      - id: check_out_the_repo
        name: Check out the repo
        uses: actions/checkout@v2.3.1
        with:
          submodules: true # Fetch Hugo
          fetch-depth: 0   # Fetch all history for .GitInfo and Lastmod

      - id: install_hugo
        name: Install Hugo
        run: |
          echo "Installing Hugo" >&2
          LATEST=$(
            cd hugo
            LATEST=$(git tag | sort -rV | head -n 1)
            git checkout $LATEST
            go install --tags extended
            mv $HOME/go/bin/hugo .
            ./hugo version >&2
            echo "${LATEST}"
          )
          echo "Installed version: ${LATEST}" >&2
          echo "::set-output name=version::${LATEST}"

      - id: create_action_yml
        name: Create action.yml
        run: |
          echo "Creating action.yml" >&2
          sed "s/%%version%%/${{ steps.install_hugo.version }}/" action.yml.tmp > action.yml
          echo "Commit new action.yml" >&2
          git add action.yml
          git commit -m "Updating action.yml with version ${LATEST}"

      - id: create_new_version_branch
        name: Create new version branch
        run: |
          git checkout -b ${{ steps.install_hugo.version }}
          git config user.email "github@utahcon.com"
          git config user.name "Utahcon"
          git push origin :refs/tags/latest
          git tag -af latest -m "Version ${{ steps.install_hugo.version }}"
          git push  origin ${{ steps.install_hugo.version }} --tags

      - name: Build and Push to Docker Hub
        uses: docker/build-push-action@v1.1.0
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
          repository: utahcon/hugo
          dockerfile: Containerfile
          tags: latest,${{ steps.install_hugo.version }}