name: Hugo Builder

on:
  push:
    branch:
      - master
      - main

jobs:
  checkout_and_build:
    name: Pull and Build Repo
    runs-on: ubuntu-latest
    steps:
      - id: check_out_the_repo
        name: Check out the repo
        uses: actions/checkout@v2.3.1
        with:
          submodules: true # Fetch Hugo
          fetch-depth: 0   # Fetch all history for .GitInfo and Lastmod

      - id: install_hugo
        name: Install Hugo
        run: |
          cd hugo
          latest=$(git tag | sort -rV | head -n 1)
          git checkout $latest
          go install --tags extended
          cp $HOME/go/bin/hugo .
          ./hugo version
          cd ..
          sed -i "s/%%version%%/${latest}/" action.yml.tmp > action.yml
          git config user.email "github@utahcon.com"
          git config user.name "Github Gitbot"
          git add action.yml
          git commit -m "Adding/updating version tag ${latest}"
          git tag -af ${latest} -m "Version ${latest}"
          git push --all
          echo "::set-output name=version::${latest}"

      - name: Build and Push to Docker Hub
        uses: docker/build-push-action@v1.1.0
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
          repository: utahcon/hugo
          dockerfile: Containerfile
          tags: latest, ${{ steps.checkout_and_build.version }}