name: Release action-hugo

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    outputs:
      version: ${{ steps.cleanup.outputs.version }}
    name: Create action-hugo release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Create action-hugo release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          body: |
            Release for Hugo version ${{ github.ref }}

      - id: cleanup
        name: Cleanup build branch
        run: |
            VERSION=$(cat BUILD_VERSION)
            echo "::set-output name=version::${VERSION}"

            git config --global user.email "github@utahcon.com"
            git config --global user.name "Adam Barrett"

            git push origin :refs/tags/build-${VERSION} || true
            git push origin :build-${VERSION} || true

  master:
    needs:
      - release
    name: Update master branch
    runs-on: ubuntu-latest
    steps:
      - name: Checkout master
        uses: action/checkout@v2
        with:
          ref: master
          token: ${{ secrets.PERSONAL_GITHUB_TOKEN }}

      - name: Update README.md
        run: |

